In [20]:
import numpy as np
print("numpy finally imported ")

numpy finally imported 


In [21]:
lst =list(range(1,25))
arr = np.array(lst)
print(type(arr))
print(type(lst))
print(arr)
print(lst)


<class 'numpy.ndarray'>
<class 'list'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]


In [22]:
arr =np.array([1,3,5,7])
arr

array([1, 3, 5, 7])

In [23]:
lst = [1,2,3,4,5]
lst

[1, 2, 3, 4, 5]

In [24]:
arr = np.arange(1,25)  # to directly convert in the array without using range 
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [25]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
arr = np.array([[[1,2,3],[4,5,6]] ,[[10,11,12],[13,14,15]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[10, 11, 12],
        [13, 14, 15]]])

In [31]:
arr = np.zeros([3,4])
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
arr = np.ones([3,4])
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
arr = np.linspace(1,10,5) # use to give the array with the comman difference which is given in the parameter with the end value that is also be given in the parameter 
arr


array([[ 1.  ],
       [ 3.25],
       [ 5.5 ],
       [ 7.75],
       [10.  ]])

In [ ]:
arr = np.linspace(1,10,5).reshape(5,1,1)  # to change the dimension of the array we use reshape
arr

array([[[ 1.  ]],

       [[ 3.25]],

       [[ 5.5 ]],

       [[ 7.75]],

       [[10.  ]]])

In [43]:
arr = np.arange(1,31).reshape(5,6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [44]:
arr.shape

(5, 6)

In [ ]:
arr = np.random.randint(1,5,9) # to find the random value
arr

array([4, 2, 1, 3, 4, 3, 1, 4, 4])

In [ ]:
arr = np.random.randint(1,10,(3,3)) # to convert the 1d array directly into 2d array
arr

array([[2, 8, 6],
       [3, 6, 9],
       [2, 5, 1]])

In [ ]:
arr = np.random.randint(1,10,(3,3,3)) # here we convert in the 3d array
arr

array([[[5, 3, 6],
        [4, 7, 6],
        [3, 5, 9]],

       [[3, 5, 8],
        [1, 1, 7],
        [8, 3, 7]],

       [[1, 5, 9],
        [3, 9, 1],
        [1, 3, 2]]])

In [ ]:
arr = np.random.random(10) # to find the random numbers
arr

array([0.01005975, 0.80205645, 0.33046091, 0.11398054, 0.22089973,
       0.29610644, 0.3432126 , 0.5022503 , 0.29777569, 0.00917411])

In [56]:
arr = np.arange(60).reshape(10,6)
arr.dtype
arr.ndim
arr.size
arr.shape

(10, 6)

In [ ]:
arr.flatten() # to convert the array into 1d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [59]:
arr.ravel() # to convert the array into 1 d array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [73]:
lst = list(range(1,13))
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [74]:
arr = np.array(lst)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [75]:
arr.T

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [77]:
arr = np.array(lst).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [78]:
arr.shape

(3, 4)

In [79]:
arr.T.shape

(4, 3)

In [80]:
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])